name: kreyative
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  lottie: ^0.3.3
  shimmer: ^1.1.1
  getflutter: ^1.0.11
  flutter_timer: ^0.0.6
  fluttertoast: ^4.0.1
  image_picker: ^0.6.5+3
  flutter_otp: ^0.3.2
  sms_receiver: ^0.3.1+1
  chewie: ^0.9.10
  video_player: ^0.10.9+1
  carousel_slider: ^2.1.0
  video_thumbnail: ^0.2.1
  google_fonts: ^1.0.0
  youtube_player_flutter: ^6.1.1
  percent_indicator: ^2.1.3
  flutter_xlider: ^3.4.0
  material_design_icons_flutter: ^4.0.5145
  flutter_zoom_plugin:
    git:
      url: git://github.com/decodedhealth/flutter_zoom_plugin.git
      ref: 0.0.7
  hexcolor: ^1.0.2
  adobe_xd: ^0.1.0
  url_launcher: ^5.4.7
  fab_circular_menu: ^1.0.0
  http: ^0.12.1
  feedback: ^0.3.0
  wiredash: ^0.2.0
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  font_awesome_flutter: ^8.8.1




dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/girl.png
    - assets/9730-rolling-pencil.json
    - assets/hello.json
    - assets/18833-refresh.json
    - assets/5th.png
    - assets/6th.png
    - assets/7th.png
    - assets/8th.png
    - assets/9th.png
    - assets/10th.png
    - assets/11th.png
    - assets/12th.png
    - assets/images.jpg
    - assets/imagestwo.jpg
    - assets/music.png
    - assets/ball.png
    - assets/puzzles.png
    - assets/drawing.png
    - assets/reading.png
    - assets/pic.png
    - assets/physics.png
    - assets/physics2.png
    - assets/biology.png
    - assets/biologytwo.png
    - assets/physicsok.png
    - assets/physicskar.png
    - assets/biologykar.png
    - assets/chemist.png
    - assets/dividers.png
    - assets/book-icon2.png
    - assets/bookwala.png
    - assets/IITwala.png
    - assets/schoolwala.png
    - assets/elementarywala.png
    - assets/physicswala.png
    - assets/hourglass.png
    - assets/stopwatch.png
    - assets/target.png
    - assets/bear.png
    - assets/bearhd.png
    - assets/bearxhd.png
    - assets/capture.png
    - assets/man.png
    - assets/cat.png
    - assets/dog.png
    - assets/bunny.png
    - assets/shark.png
    - assets/ppl.png
    - assets/kodate.png
    - assets/Flowers.mp4
    - assets/Information.mp4
    - assets/Sample.mp4
    - assets/21903-online-class-animation.json
    - assets/mememan.png
    - assets/Gyaanlogo.png
    - assets/Logotwo.png
    - assets/mansit.png
    - assets/Logogyaan.png
    - assets/goggle.png
    - assets/pencilwala.png
    - assets/penciltwo.png
    - assets/pencilthree.png
    - assets/primary.png
    - assets/abc.png
    - assets/abctwo.png
    - assets/scale.png
    - assets/scaletwo.png
    - assets/second.png
    - assets/secondtwo.png
    - assets/engi.png
    - assets/scholar.png
    - assets/one.png
    - assets/two.png
    - assets/three.png
    - assets/four.png
    - assets/fourtwo.png
    - assets/lf30_editor_anIqRX.json
    - assets/8222-success.json
    - assets/Welcome.png
    - assets/Welcometwo.png
    - assets/Welcomethree.png
    - assets/9810-notes.json
    - assets/10625-questions-and-answer.json
    - assets/face.png
    - assets/pehla.png
    - assets/dusra.png
    - assets/teesra.png
    - assets/chautha.png









  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
